### ISSUE TITLE
报毒

### ISSUE THREAD

**Issue by Riordon666** [DoubleBobCat/SUSENetwork_AutoAuth#1]
下了Windows安全中心就报毒，自己删了，笑死

**Comment by DoubleBobCat** [comment]
可行的解决方法：
1. 使用网络上的工具关闭Windows安全中心
2. 安装第三方杀毒软件，如火绒等覆盖Windows安全中心
3. 在Windows安全中心中信任本项目文件(需自行搜索方法)
